<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="49302" started-at="2020-08-08T16:36:21Z" finished-at="2020-08-08T16:37:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="49302" started-at="2020-08-08T16:36:21Z" finished-at="2020-08-08T16:37:10Z">
      <class name="extentReports2.VerifyPageTitle">
        <test-method status="FAIL" signature="VerifyTitle()[pri:0, instance:extentReports2.VerifyPageTitle@21a06946]" name="VerifyTitle" duration-ms="45552" started-at="2020-08-08T22:06:21Z" finished-at="2020-08-08T22:07:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User Not able to login Sucessfully - Invalid Credentails expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User Not able to login Sucessfully - Invalid Credentails expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at extentReports2.VerifyPageTitle.VerifyTitle(VerifyPageTitle.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyTitle -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:extentReports2.VerifyPageTitle@21a06946]" name="tearDown" is-config="true" duration-ms="3718" started-at="2020-08-08T22:07:06Z" finished-at="2020-08-08T22:07:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=VerifyTitle status=FAILURE method=VerifyPageTitle.VerifyTitle()[pri:0, instance:extentReports2.VerifyPageTitle@21a06946] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- extentReports2.VerifyPageTitle -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
